# Generated by Django 5.0 on 2025-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('road_distance', models.FloatField()),
                ('route_name', models.CharField(max_length=100)),
                ('bus_station', models.CharField(max_length=255)),
                ('brt_station', models.CharField(max_length=255)),
                ('peak_hours', models.CharField(max_length=50)),
                ('average_speed', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('landmark_nearby', models.CharField(max_length=255)),
                ('road_type', models.CharField(max_length=100)),
                ('traffic_lights_count', models.IntegerField()),
            ],
        ),
    ]
