# Generated by Django 5.1.6 on 2025-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_trafficrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
