# Generated by Django 5.1.6 on 2025-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportationdata',
            options={'verbose_name_plural': 'Transportation Data'},
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='brt_station',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='bus_station',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='landmark_nearby',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='peak_hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='road_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='road_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transportationdata',
            name='route_name',
            field=models.CharField(max_length=100),
        ),
    ]
