# Generated by Django 5.1.6 on 2025-03-16 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peak_hour_surcharge', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('traffic_light_surcharge', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distance_discount_threshold', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_discount_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fare Calculator',
                'verbose_name_plural': 'Fare Calculators',
            },
        ),
        migrations.CreateModel(
            name='FareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station', models.CharField(max_length=100)),
                ('end_station', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peak_hour_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('traffic_light_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_peak_hour', models.BooleanField(default=False)),
                ('traffic_lights', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_cost.farecalculator')),
            ],
            options={
                'verbose_name': 'Fare History',
                'verbose_name_plural': 'Fare Histories',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
